{
 "title": "Codis by changwei5",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(codis_total_qps, service)"
   },
   {
    "name": "groupaddr",
    "label": "groupaddr",
    "query": "label_values(codis_group_maxmemory, serveraddr)"
   },
   {
    "name": "proxyaddr",
    "label": "proxyaddr",
    "query": "label_values(codis_proxy_online_status, ProxyAddr)"
   }
  ]
 },
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "codis_uptime_in_seconds_Total{service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "clients",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(codis_group_connected_clients{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Proxy  Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(codis_proxy_online_status{service=~\"$service\",status=\"online\"})"
    }
   ]
  },
  {
   "title": "groups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(codis_group_used_memory{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Master",
   "type": "singlestat",
   "description": "group Master",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(codis_group_connected_slaves{service=~\"$service\",role=\"master\"})"
    }
   ]
  },
  {
   "title": "slaves",
   "type": "singlestat",
   "description": "group slaves",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(codis_group_connected_slaves{service=~\"$service\",role=\"slave\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(codis_group_used_memory{service=~\"$service\"})/sum(codis_group_maxmemory{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "avg(codis_proxy_rusage_cpu{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(codis_proxy_sessions_total{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "codis_total_qps{service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Redis Keys",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(codis_group_db0_keys{service=~\"$service\",role=\"master\"})"
    }
   ]
  },
  {
   "title": "Total_QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_total_qps{service=~\"$service\"}",
     "legendFormat": "Total_QPS"
    }
   ]
  },
  {
   "title": "total_commands_processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(codis_group_total_commands_processed{service=~\"$service\"}[1m]))",
     "legendFormat": "total_commands_processed"
    }
   ]
  },
  {
   "title": "total_connections_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(codis_group_total_connections_received{service=~\"$service\"}[1m]))",
     "legendFormat": "total_connections_received"
    }
   ]
  },
  {
   "title": "total_net_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(codis_group_total_net_input_bytes{service=~\"$service\"}[1m]))",
     "legendFormat": "net_input_bytes"
    },
    {
     "expr": "avg(rate(codis_group_total_net_output_bytes{service=~\"$service\"}[1m]))",
     "legendFormat": "net_output_bytes"
    }
   ]
  },
  {
   "title": "Total Db0 keys",
   "type": "graph",
   "description": "used_memory : 由 Redis 分配器分配的内存总量，以字节（byte）为单位\nused_memory_rss : 从操作系统的角度，返回 Redis 已分配的内存总量（俗称常驻集大小）。这个值和 top 、 ps 等命令的输出一致\nused_memory_peak : Redis 的内存消耗峰值（以字节为单位）\nused_memory_lua : Lua 引擎所使用的内存大小（以字节为单位）\nmem_fragmentation_ratio : used_memory_rss 和 used_memory 之间的比率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(codis_group_db0_keys{service=~\"$service\",role=\"master\"}[5m]))",
     "legendFormat": "Keys"
    },
    {
     "expr": "sum(increase(codis_group_db0_expires{service=~\"$service\",role=\"master\"}[5m]))",
     "legendFormat": "Expires"
    },
    {
     "expr": "avg(rate(codis_group_db0_avg_ttl{service=~\"$service\",role=\"master\"}[5m]))",
     "legendFormat": "Avg_ttl"
    }
   ]
  },
  {
   "title": "Total group_memory",
   "type": "graph",
   "description": "used_memory : 由 Redis 分配器分配的内存总量，以字节（byte）为单位\nused_memory_rss : 从操作系统的角度，返回 Redis 已分配的内存总量（俗称常驻集大小）。这个值和 top 、 ps 等命令的输出一致\nused_memory_peak : Redis 的内存消耗峰值（以字节为单位）\nused_memory_lua : Lua 引擎所使用的内存大小（以字节为单位）\nmem_fragmentation_ratio : used_memory_rss 和 used_memory 之间的比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(codis_group_maxmemory{service=~\"$service\"}[5m]))",
     "legendFormat": "maxmemory"
    },
    {
     "expr": "sum(rate(codis_group_used_memory{service=~\"$service\"}[5m]))",
     "legendFormat": "used_memory"
    },
    {
     "expr": "sum(rate(codis_group_used_memory_lua{service=~\"$service\"}[5m]))",
     "legendFormat": "used_memory_lua"
    },
    {
     "expr": "sum(rate(codis_group_used_memory_peak{service=~\"$service\"}[5m]))",
     "legendFormat": "used_memory_peak"
    },
    {
     "expr": "sum(rate(codis_group_used_memory_rss{service=~\"$service\"}[5m]))",
     "legendFormat": "used_memory_rss"
    }
   ]
  },
  {
   "title": "Total ops_per_sec ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(codis_group_instantaneous_ops_per_sec{service=~\"$service\",role=\"master\"})",
     "legendFormat": "ops_per_sec"
    }
   ]
  },
  {
   "title": "Total expired/evicted Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(codis_group_expired_keys{service=~\"$service\",role=\"master\"})",
     "legendFormat": "expired_keys"
    },
    {
     "expr": "sum(codis_group_evicted_keys{service=~\"$service\",role=\"master\"})",
     "legendFormat": "evicted_keys"
    }
   ]
  },
  {
   "title": "Total keyspace hits/misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(codis_group_keyspace_hits{service=~\"$service\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(codis_group_keyspace_misses{service=~\"$service\"}[5m]))",
     "legendFormat": "messes"
    }
   ]
  },
  {
   "title": "Total kbps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(codis_group_instantaneous_input_kbps{service=~\"$service\",role=\"master\"})*1024",
     "legendFormat": "input_kbps"
    },
    {
     "expr": "sum(codis_group_instantaneous_output_kbps{service=~\"$service\",role=\"master\"})*1024",
     "legendFormat": "output_kbps"
    }
   ]
  },
  {
   "title": "Total connected_clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(codis_group_connected_clients{service=~\"$service\"}[5m]))",
     "legendFormat": "connected_clients"
    },
    {
     "expr": "sum(increase(codis_group_blocked_clients{service=~\"$service\"}[5m]))",
     "legendFormat": "blocked_clients"
    },
    {
     "expr": "sum(increase(codis_group_rejected_connections{service=~\"$service\"}[5m]))",
     "legendFormat": "rejected_connections"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "codis_proxy_rusage_mem ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_rusage_mem{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}--mem"
    }
   ]
  },
  {
   "title": "codis_proxy_vm ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_vm_size{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}--vmSize"
    },
    {
     "expr": "codis_proxy_vm_rss{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}--vmRss"
    }
   ]
  },
  {
   "title": "Proxy QPS ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_curr_ops{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}"
    }
   ]
  },
  {
   "title": "Proxy QPS fail ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_fails_ops{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}"
    }
   ]
  },
  {
   "title": "codis_proxy_redis_ops_error ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_redis_ops_error{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}"
    }
   ]
  },
  {
   "title": "codis_proxy_num_threads ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_num_threads{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}"
    }
   ]
  },
  {
   "title": "codis_proxy_online_status ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_online_status{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}--{{status}}"
    }
   ]
  },
  {
   "title": "codis_proxy_closed_status ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "codis_proxy_closed_status{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}",
     "legendFormat": "{{ProxyAddr}}--{{status}}"
    }
   ]
  },
  {
   "title": "codis_proxy_total_ops ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(codis_proxy_total_ops{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}[5m])",
     "legendFormat": "{{ProxyAddr}}"
    }
   ]
  },
  {
   "title": "sessions ($proxyaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(codis_proxy_sessions_alive{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}[5m]))",
     "legendFormat": "{{sessions_alive}}"
    },
    {
     "expr": "sum(increase(codis_proxy_sessions_total{service=~\"$service\",ProxyAddr=~\"$proxyaddr\"}[5m]))",
     "legendFormat": "{{sessions_total}}"
    }
   ]
  },
  { "title": "Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "kbps ($groupaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "codis_group_instantaneous_input_kbps{service=~\"$service\",role=\"master\",serveraddr=~\"$groupaddr\"}*1024",
     "legendFormat": "{{serveraddr}}-input_kbps"
    },
    {
     "expr": "codis_group_instantaneous_output_kbps{service=~\"$service\",role=\"master\",serveraddr=~\"$groupaddr\"}*1024",
     "legendFormat": "{{serveraddr}}-output_kbps"
    }
   ]
  },
  {
   "title": "codis_group_maxmemory($groupaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "codis_group_maxmemory{service=~\"$service\",serveraddr=~\"$groupaddr\"}",
     "legendFormat": "{{serveraddr}}-maxmemory"
    }
   ]
  },
  {
   "title": "group used memory ($groupaddr)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "codis_group_used_memory{service=~\"$service\",serveraddr=~\"$groupaddr\"}/codis_group_maxmemory{service=~\"$service\",serveraddr=~\"$groupaddr\"}",
     "legendFormat": "{{serveraddr}}"
    }
   ]
  },
  {
   "title": "mem_fragmentation_ratio ($groupaddr)",
   "type": "graph",
   "description": "mem_fragmentation_ratio : used_memory_rss 和 used_memory 之间的比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "codis_group_mem_fragmentation_ratio{service=~\"$service\",serveraddr=~\"$groupaddr\"}",
     "legendFormat": "{{serveraddr}}"
    }
   ]
  },
  {
   "title": "mem_fragmentation_ratio ($groupaddr)",
   "type": "graph",
   "description": "mem_fragmentation_ratio : used_memory_rss 和 used_memory 之间的比率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "codis_group_mem_fragmentation_ratio{service=~\"$service\",serveraddr=~\"$groupaddr\"}",
     "legendFormat": "{{serveraddr}}"
    }
   ]
  },
  {
   "title": "codis_group_instantaneous_ops_per_sec ($groupaddr)",
   "type": "graph",
   "description": "mem_fragmentation_ratio : used_memory_rss 和 used_memory 之间的比率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "codis_group_instantaneous_ops_per_sec{service=~\"$service\",serveraddr=~\"$groupaddr\"}",
     "legendFormat": "{{serveraddr}}"
    }
   ]
  }
 ]
}